### ISSUE TITLE
This repository is confusing

### ISSUE THREAD

**Issue by julienrf** [scalacenter/scala.epfl.ch#10]
We should probably transfer issues to scala/scala.epfl.ch and remove the issues feature from this fork, or even delete the fork (we can work on the scala/scala.epfl.ch repository)

**Comment by SethTisue** [comment]
gah, I didn't even know this fork existed

**Comment by SethTisue** [comment]
attn @sjrd, who wasn't even watching this repo 😜

**Comment by sjrd** [comment]
Ah right. It *is* confusing 😅

**Comment by SethTisue** [comment]
(fwiw, at one point I recall suggesting that people would likely expect to find the Scala Center's website under scalacenter/ rather than scala/ , but Heather didn't want to move it, she liked keeping it in scala/. I don't recall her reasoning. perhaps the discussion would turn up a ticket search. I didn't have a strong feeling about it, it just seemed a bit odd to me)

**Comment by sjrd** [comment]
I manually imported all issues to scala/scala.epfl.ch. GitHub won't actually *transfer* issues across organizations :(

I have added a message in the readme to point people to scala/scala.epfl.ch.

I will now close this issue and archive the repository.
